package com.example.comic.FAKEDATA;

import android.graphics.Bitmap;

import com.example.comic.model.category;
import com.example.comic.model.comic;

import java.util.ArrayList;


public class DataComic {

     public  ArrayList<comic> listComic;
     public  ArrayList<category> listCategory;

    public DataComic() {
        ArrayList<comic> listComic=new ArrayList<>();
        ArrayList<category> listCategory=new ArrayList<>();
        Bitmap bitmap = null;
        String comic1=" Một nhà kia có hai anh em, cha mẹ đều chết cả. Hai anh em chăm lo làm lụng, nên trong nhà cũng đủ ăn. Muốn cho vui cửa vui nhà, hai người cùng lấy vợ. Nhưng từ khi có vợ, người anh sinh ra lười biếng, bao nhiêu công việc khó nhọc, đều trút cả cho hai vợ chồng người em." +
                "Hai vợ chồng người em thức khuya dậy sớm, lại cố gắng cày cấy, làm cỏ, bỏ phân, lúa tốt hơn trước, nên đến mùa, được bội thu. Thấy thế, người anh sợ em kể công chiếm lấy phần hơn, vội bàn với vợ cho hai vợ chồng người em ra ở riêng." +
                "Ra ở riêng với vợ, người em được người anh chia cho có một căn nhà tranh lụp xụp, trước nhà có một cây khế ngọt. Hai vợ chồng người em không phàn nàn một lời, hết vào rừng đốn củi đem ra chợ bán, lại đi gánh mướn, làm thuê." +
                "Còn người anh có bao nhiêu ruộng nương đều cho làm rẽ, để ngồi không hưởng sung sướng với vợ. Thấy em không ca thán, người anh cho em là ngu si, lại càng lên mặt, không lui tới nhà em và cũng không để ý gì đến em nữa." +
                "Những ngày sung sướng nhất của hai vợ chồng người em là những ngày khế chín. Quanh năm, hai vợ chồng đã chăm bón và bắt sâu, đuổi kiến cho cây khế, nên cây khế xanh mơn mởn, bóng rợp khắp mảnh vườn nhỏ bé, quả lúc lỉu cả ở những cành là sát mặt đất, trẻ lên ba cũng với tay được." +
                "Một buổi sáng, hai vợ chồng mang quang gánh và thúng bị ra gốc khế, định trèo lên hái quả đem ra chợ bán thì thấy trên ngọn cây rung động rất mạnh, như có người đang trèo. Hai vợ chồng nhìn lên thì thấy một con chim rất lớn đang ăn những quả khế chín vàng. Hai vợ chồng đứng dưới gốc cây xem chim ăn, đợi chim bay đi rồi mới trèo lên cây hái quả. Từ đấy, cứ mỗi buổi sáng tinh mơ, hai vợ chồng ra hái khế, thì đã lại thấy chim ở trên cây rồi. Thấy có người, chim vẫn cứ ăn, ung dung một lúc lâu, rồi mới vỗ cánh bay đi. Chim ăn ròng rã như thế ngót một tháng trời, cây khế vợi hẳn quả." +
                "Một hôm, đứng đợi cho chim ăn xong, người vợ nói nửa bỡn nửa thật với chim:\n “Chim ơi, chim ăn như thế thì còn gì là khế của nhà tôi nữa! Cây khế nhà tôi cũng sắp hết quả rồi đấy, chim ạ!”.\n Chim bỗng nghển cổ, nheo mắt như cười, đáp lại:\n “Ăn một quả, trả cục vàng! May túi ba gang, đem đi mà đựng”. \nChim nhắc đi nhắc lại câu ấy ba lần, rồi mới vỗ cánh bay đi." +
                "Hai vợ chồng thấy chim biết nói đã lấy làm lạ, lại thấy chim bảo mình như thế, nhắc lại cho mình đến ba lần, nghe rõ mồn một, nên càng suy nghĩ, phân vân." +
                "Nhưng rồi hai vợ chồng cũng làm theo lời chim. Người vợ lấy vài vuông vải nâu may cho chồng một cái túi, ngang dọc đúng ba gang." +
                "Sáng hôm sau, hai vợ chồng vừa ăn xong thì thấy một luồng gió mạnh cuốn cả cát bụi trước sân nhà, rồi trong chớp mắt một con chim cực kỳ lớn hạ xuống giữa sân, quay đầu vào nhà kêu lên mấy tiếng như chào hỏi. Người chồng xách cái túi ba gang ra sân, chim nằm rạp xuống, quay cổ ra hiệu cho anh ngồi lên lưng mình. Anh ngồi lên lưng chim, bám vào cổ chim thật chặt. Chim đứng dậy vươn cổ, vỗ cánh bay bổng lên trời xanh. Chim lúc bay cao, lẩn vào mây bạc; lúc bay thấp, là là trên rừng xanh, đồi núi trập trùng. Rồi chim bay ra biển cả mênh mông, sóng biếc cao ngất vật vào sườn những hòn đảo nhỏ, làm tung lên những bọt trắng xóa. Anh ngồi trên lưng chim thấy biển tuyệt mù, không biết đâu là bờ… Thốt nhiên chim bay vào một hòn đảo toàn đá trắng, đá xanh, đá đỏ, đã ngũ sắc, phản chiếu ánh sáng rực rỡ, anh chưa từng thấy bao giờ. Chim bay một vòng thật rộng xung quanh đảo như muốn tìm một nơi hạ cánh, rồi bay những vòng hẹp hơn, là là trên các ngọn đá, lắm lúc anh tưởng như mình sắp bị va vào những tảng đá khổng lồ. Bay đến trước mặt cái hang rộng và sâu, chim từ từ hạ xuống. Ðặt chân xuống đảo, anh nhìn ngó khắp nơi, tuyệt nhiên không thấy một sinh vật nào, không có đến một ngọn cỏ hay một mống chim sâu." +
                "Chim ra hiệu bảo anh vào hang, muốn lấy gì thì lấy. Ở ngay cửa hang, anh đã thấy toàn những thứ đá trong như thủy tinh và hổ phách đủ các mầu; có thứ xanh như mắt mèo, có thứ đỏ ối như mặt trời, còn vàng bạc thì nhiều như sỏi đá. Thấy hang sâu và rộng, anh không dám vào sợ lạc. Anh nhặt một ít vàng và kim cương bỏ vào túi ba gang, rồi trèo lên lưng chim, ra hiệu cho chim bay về." +
                "Chim tỏ vẻ vui mừng, gật gật cái đầu, vươn cổ kêu vài tiếng, rồi vỗ cánh bay lên trời xanh, bay qua biển, qua rừng, qua núi. Mặt trời mới vừa đứng bóng, chim đã hạ cánh xuống cái vườn nhỏ có cây khế ngọt. Người vợ thấy chồng về bình yên, mừng rỡ vô cùng, chạy ra vuốt lông chim, tỏ ý cảm ơn, ra hiệu mời chim bay lên cây khế giải khát. Chim bay lên cây khế ăn một lúc, rồi kêu ba tiếng như chào vợ chồng người nông dân, rồi bay đi. Từ đấy, lâu lâu chim mới lại đến ăn khế." +
                "Tiếng đồn hai vợ chồng người em thốt nhiên giàu có bay đến tai hai vợ chồng người anh. Hai vợ chồng người anh vội vã đến chơi nhà em để dò xét. Nghe em thật thà kể chuyện, người anh gạ đổi hết tài sản của mình để lấy túp lều tranh và cây khế. Hai vợ chồng chỉ lo người em không chịu đổi, không ngờ người em vui vẻ ưng thuận ngay." +
                "Hai vợ chồng người anh mừng rỡ như mở cờ trong bụng, lập tức giao hết tài sản của mình cho em, và sáng hôm sau dọn ngay đến ở túp lều tranh trên mảnh vườn nhỏ có cây khế ngọt. đến ở mảnh vườn chật hẹp, hai vợ chồng người anh không làm việc gì cả. Còn được ít tiền hai vợ chồng đem tiêu dần, cả ngày chỉ nằm khểnh ngoài hè, hí hửng nhìn lên cây khế, chờ chim bay đến. Một buổi sáng, có một luồng gió mạnh tạt vào nhà, rồi hai vợ chồng thấy ngọn cây khế rung chuyển. Hai người hớt hải chạy ra sân, vội nhìn lên cây thì quả nhiên thấy một con chim lớn đang ăn khế." +
                "Chim mới ăn vài quả, hai vợ chồng đã tru tréo lên: \n“Cả nhà chúng tôi trông vào có cây khế, bây giờ chim ăn tào ăn huyệt như thế thì chúng tôi còn trông cậy vào đâu!”.\n Chim liền đáp: \n“Ăn một quả, trả cục vàng. May túi ba gang, đem đi mà đựng”.\n rồi chim bay vụt đi." +
                "Hai vợ chồng người anh mừng quá, cuống quýt vái theo chim, rồi bàn nhau may túi, cãi cọ om sòm. Mới đầu, hai người định may thật nhiều túi, sau lại sợ chim không đưa đi, nên rút cục cũng chỉ may một cái túi như người em, nhưng may to gấp ba, mỗi chiều chín gang, thành một cái tay nải lớn." +
                "Sáng hôm sau, chim hạ cánh xuống sân trước túp lều tranh. Người anh đang ăn, thấy chim bay đến, bỏ cả ăn hấp tấp chạy ra, tay xách cái túi lớn trèo tót lên lưng chim, còn người vợ vái lấy vái để chim thần. Chim cất cánh bay bổng lên mây xanh, qua núi qua biển cả, rồi cũng hạ cánh xuống cái đảo khi trước." +
                "Trên lưng chim bước xuống, người anh hoa cả mắt về những ánh ngũ sắc ở các loại kim cương và ngọc quý chiếu ra. Ðến khi vào hang, người anh lại càng mê mẩn tâm thần, quên cả đói cả khát, cố nhặt vàng và kim cương cho thật đầy tay nải, lại buộc đầu ống quần và tay áo cho thật chặt rồi nhồi nhét đầy cả hai tay áo và hai ống quần, đến nỗi nặng quá, chàng ta cố kéo lê từng bước mà vẫn chưa ra được khỏi hang." +
                "Chim đợi lâu quá, chốc chốc lại kêu lên vài tiếng vang cả đảo, thúc giục anh chàng ra về. Mãi gần chiều, anh ta mới kéo được cái tay nải đầy vàng và kim cương đến chỗ chim đang đợi. Muốn cho khỏi rơi, anh ta đặt tay nải dưới cánh chim, rồi lấy dây thừng buộc chặt tay nải vào lưng chim và vào cổ mình." +
                "Chim vỗ cánh bay lên, nhưng vì nặng quá, mới bay lên khỏi mặt đất một ít lại sa xuống. Sau chim cố gắng đạp hai chân thật mạnh xuống đất, vươn cổ bay bổng lên. Anh chàng ngồi trên lưng chim khấp khởi mừng thầm, cho là chỉ trong giây phút mình sẽ về đến nhà, sẽ có nhà cao cửa rộng, vườn ruộng khắp nơi, tiêu pha hết đời thật hoang toàng cũng không hết của." +
                "Lúc ấy, chim đã bay trên biển cả. Trời trở gió, những con sóng xám xì cất cao lên bằng mấy nóc nhà. Chim bay ngược gió rất là nhọc mệt, cổ gập hẳn xuống, hai cánh mỗi lúc một yếu dần. Túi vàng lớn thốt nhiên bị gió hất mạnh vào cánh chim. Chim buông xuôi hai cánh, đâm bổ từ lưng trời xuống biển. Chỉ trong chớp mắt, người anh bị sóng cuốn đi, cái túi lớn và những ống quần, tay áo chứa đầy vàng và châu báu dìm anh ta rất mau xuống đáy biển." +
                "Còn chim chỉ bị ướt lông, ướt cánh một lúc, rồi chim lại vùng lên khỏi mặt nước, bay về núi, về rừng.";
        String comic2=" Ngày xưa, có một ông già nhà quê có một cô gái đẹp. Trong nhà phải thuê một đầy tớ trai, ông ta muốn lợi dụng nó làm việc khỏi trả tiền, mới bảo nó rằng: \n“ Mày chịu khó làm ăn với tao rồi tao gả con gái cho”\n. Người ở mừng lắm, ra sức làm lụng tới khuya không nề hà mệt nhọc. Nó giúp việc được ba năm, nhà ông ta mỗi ngày một giàu có." +
                "Ông nhà giàu không còn nghĩ đến lời hứa cũ nữa, đem con gái gả cho con một nhà phú hộ khác ở trong làng." +
                "Sáng hôm sắp đưa dâu, ông chủ gọi đứa ở lên lừa nó một lần nữa, bảo rằng: \n“ Bây giờ mày lên rừng tìm cho ra một cây tre có trăm đốt đem về đây làm đũa ăn cưới, thì tao cho mày lấy con gái tao ngay”\n." +
                "Đứa ở tưởng thật, vác dao đi rừng. Nó kiếm khắp nơi, hết rừng này qua rừng nọ, không tìm đâu thấy có cây tre đủ trăm đốt. Buồn khổ quá, nó ngồi một chỗ ôm mặt khóc. Bỗng thấy có một ông lão râu tóc bạc phơ, tay cầm gậy trúc hiện ra bảo nó: “\n  Tại sao con khóc, hãy nói ta nghe, ta sẽ giúp cho”\n. Nó bèn đem đầu đuôi câu chuyện ông phú hộ hứa gả con gái cho mà kể lại. Ông lão nghe xong, mới bảo rằng: “\nCon đi chặt đếm đủ trăm cái đốt tre rồi đem lại đây ta bảo”." +
                "Nó làm theo y lời dặn, ông dạy nó đọc: “ \n Khắc nhập, khắc nhập\n” (vào ngay, vào ngay) đủ ba lần, thì một trăm khúc tre tự nhiên dính lại với nhau thành một cây trẻ đủ một trăm đốt. Nó mừng quá, định vác về, nhưng cây tre dài quá, vướng không đi được. Ông lão bảo nó đọc: \n“Khắc xuất, khắc xuất”\n (ra ngay, ra ngay) đúng ba lần thì cây tre trăm đốt lại rời ra ngay từng khúc." +
                "Nó bèn bó cả lại mà gánh về nhà. Đến nơi thấy hai họ đang ăn uống vui vẻ, sắp đến lúc rước dâu, nó mới hay là ông chủ đã lừa nó đem gả con gái cho người ta rồi. Nó không nói gì, đợi lúc nhà trai đốt pháo cưới, bèn đem một trăm khúc tre xếp dài dưới đất, rồi lẩm bẩm đọc: \n“Khắc nhập, khắc nhập”\n cho liền lại thành một cây tre trăm đốt, đoạn gọi ông chủ đến bảo là đã tìm ra được, và đòi gả con gái cho nó. Ông chủ lấy làm lạ cầm cây tre lên xem, nó đọc luôn: \n“Khắc nhập, khắc nhập”\n, thì ông ta bị dính liền ngay vào cây tre, không làm sao gỡ ra được. Ông thông gia thấy vậy chạy đến, định gỡ cho, nó lại đọc luôn: \n“Khắc nhập, khắc nhập”\n, thì cả ông cũng bị dính theo luôn, không lôi ra được nữa." +
                "Hai họ thấy thế không còn ai dám lại gần nó nữa. Còn hai ông kia không còn biết làm thế nào đành van lạy xin nó thả ra cho. Ông chủ hứa gả con gái cho nó, ông thông gia xin về nhà ngay, nó để cho cả hai thề một hồi rồi nó mới đọc: \n“Khắc xuất, khắc xuất”\n thì hai ông rời ngay cây tre, và cây tre cũng rời ra trăm khúc." +
                "Mọi người đều lấy làm khiếp phục đứa ở, ông chủ vội gả con gái cho nó, và từ đó không còn dám khinh thường nó nữa.";
        String comic3=" Vào thời giặc Minh đặt ách đô hộ ở nước Nam, chúng coi dân ta như cỏ rác, làm nhiều điều bạo ngược, thiên hạ căm giận chúng đến xương tủy. Bấy giờ ở vùng Lam Sơn, nghĩa quân nổi dậy chống lại chúng, nhưng trong buổi đầu thế lực còn non yếu nên nhiều lần nghĩa quân bị thua. Thấy vậy, đức Long Quân quyết định cho nghĩa quân mượn thanh gươm thần để họ giết giặc." +

                "Hồi ấy, ở Thanh Hóa có một người làm nghề đánh cá tên là Lê Thận. Một đêm nọ, Thận thả lưới ở một bến vắng như thường lệ. Khi kéo lưới lên, chàng thấy nằng nặng, trong bụng mừng thầm, chắc là có cá to. Nhưng khi thò tay vào bắt cá, Thận chỉ thấy có một thanh sắt; chàng vứt luôn xuống nước, rồi lại thả lưới ở một chỗ khác." +
                "Lần thứ hai cất lưới lên cũng thấy nặng tay; Thận không ngờ thanh sắt vừa rồi lại chui vào lưới mình. Chàng lại nhặt lên và ném xuống sông. Lần thứ ba, lại vẫn thanh sắt ấy mắc vào lưới. Lấy làm quái lạ, Thận đưa lại mồi lửa nhìn xem. Bỗng chàng reo lên:\n" +
                "– Ha ha! Một lưỡi gươm!\n" +
                "Về sau Thận gia nhập đoàn quân khởi nghĩa Lam Sơn. Chàng hăng hái gan dạ không nề nguy hiểm. Một hôm chủ tướng Lê Lợi cùng mấy người tùy tòng đến nhà Thận. Trong túp lều tối om, thanh sắt hôm đó tự nhiên sáng rực lên ở xó nhà. Lấy làm lạ, Lê Lợi cầm lấy xem và thấy có hai chữ “Thuận Thiên” khắc sâu vào lưỡi gươm. Song tất cả mọi người vẫn không biết đó là báu vật." +
                "Một hôm, bị giặc đuổi, Lê Lợi và các tướng chạy tháo thân mỗi người một ngả. Lúc đi qua một khu rừng, Lê Lợi bỗng thấy một ánh sáng lạ trên ngọn cây đa. Ông trèo lên mới biết đó là một cái chuôi gươm nạm ngọc. Nhớ đến lưỡi gươm ở nhà Lê Thận, Lê Lợi rút lấy chuôi giắt vào lưng." +
                "Ba ngày sau, Lê Lợi gặp lại tất cả các bạn trong đó có Lê Thận. Lê Lợi mới đem chuyện bắt được chuôi gươm kể lại cho mọi người nghe. Khi đem tra gươm vào chuôi thì vừa như in." +
                "Lê Thận nâng gươm lên ngang đầu nói với Lê Lợi:\n" +
                "– Ðây là Trời có ý phó thác cho minh công làm việc lớn. Chúng tôi nguyện đem xương thịt của mình theo minh công, cùng với thanh gươm thần này để báo đền Tổ quốc!\n" +
                "Từ đó nhuệ khí của nghĩa quân ngày một tăng tiến. Trong tay Lê Lợi, thanh gươm thần tung hoành khắp các trận địa, làm cho quân Minh bạt vía. Uy thanh của nghĩa quân vang khắp nơi. Họ không phải trốn tránh như trước mà xông xáo đi tìm giặc. Họ không phải ăn uống khổ cực như trước nữa, đã có những kho lương của giặc mới cướp được tiếp tế cho họ. Gươm thần đã mở đường cho họ đánh tràn ra mãi, cho đến lúc không còn bóng một tên giặc trên đất nước." +
                "Một năm sau khi đuổi giặc Minh, một hôm Lê Lợi – bấy giờ đã làm vua – cưỡi thuyền rồng dạo quanh hồ Tả Vọng trước kinh thành. Nhân dịp đó, Long Quân sai rùa vàng lên đòi lại thanh gươm thần. Khi chiếc thuyền rồng tiến ra giữa hồ, tự nhiên có một con rùa lớn nhô đầu và mai lên khỏi mặt nước. Theo lệnh vua, thuyền đi chậm lại. Ðứng ở mạn thuyền, vua thấy lưỡi gươm thần đeo bên người tự nhiên động đậy. Con rùa vàng không sợ người, nhô đầu lên cao nữa và tiến về phía thuyền vua. Nó đứng nổi trên mặt nước và nói\n: -Xin bệ hạ hoàn gươm lại cho Long Quân!.\n" +
                "Vua rút gươm quẳng về phía rùa vàng. Nhanh như cắt, rùa há miệng đớp lấy thanh gươm và lặn xuống nước. Gươm và rùa đã chìm đáy nước, người ta vẫn còn thấy vật gì sáng le lói dưới mặt hồ xanh.";
        comic caykhe=new comic("Sự tích cây khế",comic1, bitmap,1,"img/caykhe2.jpg",1);
        comic caytre=new comic("Cây tre trăm đốt",comic2,bitmap,1,"img/caytre.jpg",2);
        comic hoguom=new comic("Sự tích hồ gươm",comic3,bitmap,1,"img/hoguom2.png",3);
        listComic.add(caykhe);
        listComic.add(caytre);
        listComic.add(hoguom);
        listCategory.add(new category(1,"Cổ tích dân gian"));
        this.listCategory=listCategory;
        this.listComic=listComic;
    }
}
